modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "omnicraft"
version = "1.18.2-0.0.1d"
displayName = "Omnicraft"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="omnicraft.png"
#credits="Thanks for this example mod goes to Java"
authors = "RealDarkStudios"
description = '''
Official Omnicraft Mod for Forge 1.18.2

Your Version: 0.0.1d
'''

[[dependencies.omnicraft]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.omnicraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
